### PR TITLE
Upgrade ganache-core to 2.4.0

### PR DESCRIPTION
**Pull request by snario**
Fixes https://github.com/EthWorks/Waffle/issues/79

### CODE REVIEW

**Comment by marekkirejczyk** [comment]
Good stuff. The CI is failing thou :( 
I am traveling. Will look into it as soon as I have a moment.

**Comment by snario** [comment]
I think `yarn` just needs to be run: did this on the GitHub UI

**Comment by marekkirejczyk** [comment]
Ok, fixed and merged in #81, will release soon (can't push npm from the airport for some reason)

**Comment by marekkirejczyk** [comment]
Released in 2.0.6

**Pull request closed without merging**
