### PR TITLE
Add revert with reason functionality for mock contracts

### PR DESCRIPTION
**Pull request by PaulRBerg**
Not being able to revert with a reason on a mock contract is prohibitively limiting.

Say you have contract A and contract B. The latter depends on the former. Say that the former throws specific errors depending on the state of the properties in the two contracts. If I mock contract A, I have to modify a lot of tests to revert with "Mock revert" instead of my bespoke error messages.

This PR does the following:

+ Adds a new `revertReason` property in the `MockCall` struct
+ Changes the signature of the `__waffle__mockReverts` function, by adding a second parameter `revertReason`
+ Adds a new function `revertWithReason` in the object returned by the `stub` function - which makes my change backwards-compatible!
+ Modifies the tests so that they work with the updated `__waffle__mockReverts` function

### CODE REVIEW

**Comment by marekkirejczyk** [comment]
@PaulRBerg Good stuff, merging. Would add a PR with docs?

**Comment by marekkirejczyk** [comment]
Released in [3.0.3](https://github.com/EthWorks/Waffle/releases/tag/3.0.3)

**Comment by PaulRBerg** [comment]
Thanks for merging, Marek!

> Would add a PR with docs?

I could do this, in case you haven't done it in the meantime?

**Comment by marekkirejczyk** [comment]
Released in Waffle 3.1.0. Didn't have a chance to work on docs yet. Would love to get some help :)

**Comment by PaulRBerg** [comment]
Done: https://github.com/EthWorks/Waffle/pull/366.

**Pull request merged**
